### ISSUE TITLE
Improve: Put a default name based on queue name

### ISSUE THREAD

**Issue by SRWieZ** [SRWieZ/queue-size-health-check#4]
This code returns an error 
```php
QueueSizeCheck::new() ->queue('static_cache', 100),
QueueSizeCheck::new()->queue('default', 100),
```

>Spatie\Health\Exceptions\DuplicateCheckNamesFound
>You registered checks with a non-unique name: `QueueSize`. Each check should be unique. If you really want to use the same check class twice, make sure to call `name()` on them to ensure that they all have unique names.

The current solution is to manually give it a name for each check:

```php
QueueSizeCheck::new() ->queue('static_cache', 100)->name('Queue size (static_cache)'),
QueueSizeCheck::new()->queue('default', 100)->name('Queue size (default)'),
```

A nice PR would be to put a default name based on queue name

**Comment by binarygeotech** [comment]
@SRWieZ a PR has been created for this; #6
